name: Get Team and Game Data Runner

on: 
  schedule:
    - cron: "0 8 * * *"  # Runs daily at 0800
    - cron: "0 20 * * *" # Runs daily at 2000
  workflow_dispatch:

jobs:
  run-get-team-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run Get Team Data
        run: |
          python backend/scripts/get-nfl-team-data.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_KEY: ${{ secrets.DATABASE_KEY }}
      
      - name: Run Get Game Data
        run: |
          python backend/scripts/get-weekly-scoreboard.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_KEY: ${{ secrets.DATABASE_KEY }}